---
driver:
  name: vagrant
  network:
    - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
#  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
#  - name: ubuntu-16.04
  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[awesome_customers_rhel::default]
#    verifier:
#      inspec_tests:
#        - test/recipes
    attributes:
      awesome_customers_rhel:
        database:
          root_password: 'mysql_root_password'
          admin_password: 'mysql_admin_password'
